apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbor-dev
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thumbor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: config-thumbor-dev
        image: minimalcompact/thumbor:latest
        imagePullPolicy: Always
        name: thumbor
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
